# Generated by Django 2.1.14 on 2020-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('ip', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
